name: spc_app
description: A new Flutter application for SPC (Statistical Process Control).

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Adjust this according to your Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.20.1
  google_fonts: ^6.2.1
  excel: ^4.0.6
  file_selector: ^1.0.3
  file_picker: ^8.1.2
  flutter_bloc: ^8.0.1
  logger: ^2.5.0
  pdf: ^3.10.5
  path_provider: ^2.0.12
  shared_preferences: ^2.2.2
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.1.0  # For loading spinner
  fl_chart: ^0.69.2
  share_plus: ^7.0.0
  permission_handler: ^11.3.1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

